site_name: CTF Writeups
plugins:
  - search
  - social
  - privacy
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-authors
  - blog:
      post_url_format: "{slug}"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
theme:
  name: material
  features:
    - content.code.annotate
    - header.autohide
    - announce.dismiss
plugins:
  - blog
nav:
  - Blog:
    - blog/index.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.keys